language: java

jdk:
- openjdk10

addons:
 sonarcloud:
  organization: domenicoverde
  token:
    secure: "t9ngFJJLLmDUav9sE8eNCyHwXde0oAAmILr4Vi+PEqCK6Q5Oyop/4T8Gy1XoNd1i5eZlUHi588kOMHfcmMpT/uMlmVNeqc4d1I1bGtVePF5UhLHSzjs0MqnkkyhCeb0oJZL/Dnnp0YUHaQBznb6pHYcMmx3EtEj7tOmqMnlFiBTiZJnhFTd/cYYtti0XJtHgpUYctA41s8XNcmV6HK5olm8EP6wh8/fCz8Y+MGOTYpNomI3X/SD68PEojnmCxirR0u3VxnqyRJYea4807lP1j3wNzpef9N87TEjyfLSapcas1/yT6uaUW+UwTSCRY64PZQNihBUFj5aclJiawt/omDAkUwUYfzNawbJhA3O0RY/PkAK04DNO+6BlFlLuK05aYSeTGQVnnIyUXSiS1lQgR0gZa3piXh4M1gEfSRFmFBgdPJVw2/EX0Q1+hn5Y0qjXHlY7F0BCakEmF55Gc7OW60y6JuEF5MErDwonNIuA+mLQxQJgYevQBf09nO6ybzcxSYd6kzXNLWD946pwUnnOfBMdSiZMgK1ZNOj2BYMH3Dx9KWwrUEOjIpXaKm1q/zZxG4EW+rr5B9Ycbqh/0wnmABrPOxAmrV6cPyNdAq5AkqM2Yel5IU7/ft8wtHOO8JEhwuIOr8kx7wO4wbOpj7KmLm1sXi1larIR8hX0nT8UBxA="

install: skip

script: 
- mvn sonar:sonar -Dsonar.projectKey=DomenicoVerde_bookkeeper -pl .,bookkeeper-server
